import { baseUrl } from "@/api/baseUrl";
import Blogs from "../components/home/Blogs";
import Hero from "../components/home/Hero";

export const metadata = {
  title: "انفوا للتقنية",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <Hero />
      <Blogs />
    </>
  );
}
